/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface CreateUser201Response
 */
export interface CreateUser201Response {
    /**
     * 
     * @type {User}
     * @memberof CreateUser201Response
     */
    data?: User;
}

/**
 * Check if a given object implements the CreateUser201Response interface.
 */
export function instanceOfCreateUser201Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateUser201ResponseFromJSON(json: any): CreateUser201Response {
    return CreateUser201ResponseFromJSONTyped(json, false);
}

export function CreateUser201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUser201Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : UserFromJSON(json['data']),
    };
}

export function CreateUser201ResponseToJSON(value?: CreateUser201Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UserToJSON(value.data),
    };
}

