/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserAllOfAttributes
 */
export interface CreateUserAllOfAttributes {
    /**
     * User's name
     * @type {string}
     * @memberof CreateUserAllOfAttributes
     */
    name: string;
    /**
     * User's age
     * @type {number}
     * @memberof CreateUserAllOfAttributes
     */
    age: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreateUserAllOfAttributes
     */
    role: boolean;
}

/**
 * Check if a given object implements the CreateUserAllOfAttributes interface.
 */
export function instanceOfCreateUserAllOfAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "age" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function CreateUserAllOfAttributesFromJSON(json: any): CreateUserAllOfAttributes {
    return CreateUserAllOfAttributesFromJSONTyped(json, false);
}

export function CreateUserAllOfAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserAllOfAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'age': json['age'],
        'role': json['role'],
    };
}

export function CreateUserAllOfAttributesToJSON(value?: CreateUserAllOfAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'age': value.age,
        'role': value.role,
    };
}

