/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserKey
 */
export interface CreateUserKey {
    /**
     * 
     * @type {string}
     * @memberof CreateUserKey
     */
    type: CreateUserKeyTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateUserKey
     */
    id: string;
}


/**
 * @export
 */
export const CreateUserKeyTypeEnum = {
    CreateUsers: 'create-users'
} as const;
export type CreateUserKeyTypeEnum = typeof CreateUserKeyTypeEnum[keyof typeof CreateUserKeyTypeEnum];


/**
 * Check if a given object implements the CreateUserKey interface.
 */
export function instanceOfCreateUserKey(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CreateUserKeyFromJSON(json: any): CreateUserKey {
    return CreateUserKeyFromJSONTyped(json, false);
}

export function CreateUserKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function CreateUserKeyToJSON(value?: CreateUserKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

