/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateUserAllOfAttributes } from './CreateUserAllOfAttributes';
import {
    CreateUserAllOfAttributesFromJSON,
    CreateUserAllOfAttributesFromJSONTyped,
    CreateUserAllOfAttributesToJSON,
} from './CreateUserAllOfAttributes';

/**
 * 
 * @export
 * @interface CreateUserAllOf
 */
export interface CreateUserAllOf {
    /**
     * 
     * @type {CreateUserAllOfAttributes}
     * @memberof CreateUserAllOf
     */
    attributes: CreateUserAllOfAttributes;
}

/**
 * Check if a given object implements the CreateUserAllOf interface.
 */
export function instanceOfCreateUserAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function CreateUserAllOfFromJSON(json: any): CreateUserAllOf {
    return CreateUserAllOfFromJSONTyped(json, false);
}

export function CreateUserAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributes': CreateUserAllOfAttributesFromJSON(json['attributes']),
    };
}

export function CreateUserAllOfToJSON(value?: CreateUserAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributes': CreateUserAllOfAttributesToJSON(value.attributes),
    };
}

