/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Errors } from './Errors';
import {
    ErrorsFromJSON,
    ErrorsFromJSONTyped,
    ErrorsToJSON,
} from './Errors';

/**
 * 
 * @export
 * @interface GetUsersList400Response
 */
export interface GetUsersList400Response {
    /**
     * 
     * @type {Array<Errors>}
     * @memberof GetUsersList400Response
     */
    errors: Array<Errors>;
}

/**
 * Check if a given object implements the GetUsersList400Response interface.
 */
export function instanceOfGetUsersList400Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "errors" in value;

    return isInstance;
}

export function GetUsersList400ResponseFromJSON(json: any): GetUsersList400Response {
    return GetUsersList400ResponseFromJSONTyped(json, false);
}

export function GetUsersList400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsersList400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': ((json['errors'] as Array<any>).map(ErrorsFromJSON)),
    };
}

export function GetUsersList400ResponseToJSON(value?: GetUsersList400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': ((value.errors as Array<any>).map(ErrorsToJSON)),
    };
}

