/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface GetUsersList200Response
 */
export interface GetUsersList200Response {
    /**
     * 
     * @type {Array<User>}
     * @memberof GetUsersList200Response
     */
    data?: Array<User>;
}

/**
 * Check if a given object implements the GetUsersList200Response interface.
 */
export function instanceOfGetUsersList200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetUsersList200ResponseFromJSON(json: any): GetUsersList200Response {
    return GetUsersList200ResponseFromJSONTyped(json, false);
}

export function GetUsersList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsersList200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(UserFromJSON)),
    };
}

export function GetUsersList200ResponseToJSON(value?: GetUsersList200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(UserToJSON)),
    };
}

