/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserAllOfAttributes
 */
export interface UpdateUserAllOfAttributes {
    /**
     * User's name
     * @type {string}
     * @memberof UpdateUserAllOfAttributes
     */
    name?: string;
    /**
     * User's age
     * @type {number}
     * @memberof UpdateUserAllOfAttributes
     */
    age?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserAllOfAttributes
     */
    role?: boolean;
}

/**
 * Check if a given object implements the UpdateUserAllOfAttributes interface.
 */
export function instanceOfUpdateUserAllOfAttributes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateUserAllOfAttributesFromJSON(json: any): UpdateUserAllOfAttributes {
    return UpdateUserAllOfAttributesFromJSONTyped(json, false);
}

export function UpdateUserAllOfAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserAllOfAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'age': !exists(json, 'age') ? undefined : json['age'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function UpdateUserAllOfAttributesToJSON(value?: UpdateUserAllOfAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'age': value.age,
        'role': value.role,
    };
}

