/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateUserAllOfAttributes } from './UpdateUserAllOfAttributes';
import {
    UpdateUserAllOfAttributesFromJSON,
    UpdateUserAllOfAttributesFromJSONTyped,
    UpdateUserAllOfAttributesToJSON,
} from './UpdateUserAllOfAttributes';

/**
 * 
 * @export
 * @interface UpdateUserAllOf
 */
export interface UpdateUserAllOf {
    /**
     * 
     * @type {UpdateUserAllOfAttributes}
     * @memberof UpdateUserAllOf
     */
    attributes: UpdateUserAllOfAttributes;
}

/**
 * Check if a given object implements the UpdateUserAllOf interface.
 */
export function instanceOfUpdateUserAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function UpdateUserAllOfFromJSON(json: any): UpdateUserAllOf {
    return UpdateUserAllOfFromJSONTyped(json, false);
}

export function UpdateUserAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributes': UpdateUserAllOfAttributesFromJSON(json['attributes']),
    };
}

export function UpdateUserAllOfToJSON(value?: UpdateUserAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributes': UpdateUserAllOfAttributesToJSON(value.attributes),
    };
}

