/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserKey
 */
export interface UpdateUserKey {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserKey
     */
    type: UpdateUserKeyTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserKey
     */
    id: string;
}


/**
 * @export
 */
export const UpdateUserKeyTypeEnum = {
    UpdateUsers: 'update-users'
} as const;
export type UpdateUserKeyTypeEnum = typeof UpdateUserKeyTypeEnum[keyof typeof UpdateUserKeyTypeEnum];


/**
 * Check if a given object implements the UpdateUserKey interface.
 */
export function instanceOfUpdateUserKey(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UpdateUserKeyFromJSON(json: any): UpdateUserKey {
    return UpdateUserKeyFromJSONTyped(json, false);
}

export function UpdateUserKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function UpdateUserKeyToJSON(value?: UpdateUserKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

