/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UploadUser200Response
 */
export interface UploadUser200Response {
    /**
     * 
     * @type {User}
     * @memberof UploadUser200Response
     */
    data?: User;
}

/**
 * Check if a given object implements the UploadUser200Response interface.
 */
export function instanceOfUploadUser200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UploadUser200ResponseFromJSON(json: any): UploadUser200Response {
    return UploadUser200ResponseFromJSONTyped(json, false);
}

export function UploadUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadUser200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : UserFromJSON(json['data']),
    };
}

export function UploadUser200ResponseToJSON(value?: UploadUser200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UserToJSON(value.data),
    };
}

