/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateUser } from './CreateUser';
import {
    CreateUserFromJSON,
    CreateUserFromJSONTyped,
    CreateUserToJSON,
} from './CreateUser';

/**
 * 
 * @export
 * @interface UploadUserRequest
 */
export interface UploadUserRequest {
    /**
     * 
     * @type {CreateUser}
     * @memberof UploadUserRequest
     */
    data?: CreateUser;
}

/**
 * Check if a given object implements the UploadUserRequest interface.
 */
export function instanceOfUploadUserRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UploadUserRequestFromJSON(json: any): UploadUserRequest {
    return UploadUserRequestFromJSONTyped(json, false);
}

export function UploadUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : CreateUserFromJSON(json['data']),
    };
}

export function UploadUserRequestToJSON(value?: UploadUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CreateUserToJSON(value.data),
    };
}

