/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserAllOfAttributes } from './UserAllOfAttributes';
import {
    UserAllOfAttributesFromJSON,
    UserAllOfAttributesFromJSONTyped,
    UserAllOfAttributesToJSON,
} from './UserAllOfAttributes';

/**
 * 
 * @export
 * @interface UserAllOf
 */
export interface UserAllOf {
    /**
     * 
     * @type {UserAllOfAttributes}
     * @memberof UserAllOf
     */
    attributes: UserAllOfAttributes;
}

/**
 * Check if a given object implements the UserAllOf interface.
 */
export function instanceOfUserAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function UserAllOfFromJSON(json: any): UserAllOf {
    return UserAllOfFromJSONTyped(json, false);
}

export function UserAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributes': UserAllOfAttributesFromJSON(json['attributes']),
    };
}

export function UserAllOfToJSON(value?: UserAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributes': UserAllOfAttributesToJSON(value.attributes),
    };
}

