/* tslint:disable */
/* eslint-disable */
/**
 * users-svc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserKey
 */
export interface UserKey {
    /**
     * 
     * @type {string}
     * @memberof UserKey
     */
    type: UserKeyTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UserKey
     */
    id: string;
}


/**
 * @export
 */
export const UserKeyTypeEnum = {
    Users: 'users'
} as const;
export type UserKeyTypeEnum = typeof UserKeyTypeEnum[keyof typeof UserKeyTypeEnum];


/**
 * Check if a given object implements the UserKey interface.
 */
export function instanceOfUserKey(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UserKeyFromJSON(json: any): UserKey {
    return UserKeyFromJSONTyped(json, false);
}

export function UserKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function UserKeyToJSON(value?: UserKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

